### ISSUE TITLE
Add navigation by section.

### ISSUE THREAD

**Issue by Rebryk** [Karma-Police/english-reader#25]
- [x] draw section list
- [x] add sections title
- [x] add subsections
- [x] dump content to improve speed
- [x] fix bug with sections page

**Comment by Rebryk** [comment]
Implemented simple section navigation.

**Todo**
- [ ] add sections title
- [ ] add subsections
- [ ] change icon location
